baseURL = "https://dhost.dev"
languageCode = "en-us"
title = "DHost"
enableRobotsTXT = true
enableGitInfo = false

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "/imgs/dhostlogo.png"

# meta data
author = "Dhost"
description = "Dhost"

# Gestion des langues : FR / EN
[Languages]
############ 1 - Site en FRANCAIS
[Languages.fr]
languageCode = "fr-fr"
title = "Dhost"
dateFormat = "2 Janvier 2006"
home = "EN Home"
logo = "/imgs/dhostlogo.png"

# Hero Area Section
[Languages.fr.params.hero]
enable  = true
heading = "Hébergement décentralisé pour votre"
headingWebsite = "site web"
description = "Dhost facilite la création de sites web et d'applications sur le nouveau web ouvert : sans permission, sans confiance, résistant à la censure et libre de tout contrôle centralisé."
button  = true
btnGetStartedText = "Commencer"
btnGetStartedURL  = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
btnLearnMoreText = "En savoir plus"
btnLearnMoreURL  = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

# Deploy Section
[Languages.fr.params.process]
title = "Décentraliser votre app"
uploadText = "Choisissez la source de votre site web"
buildTitle = "Choisissez les options de build"
buildText = "Adaptez vos paramètres pour préparer le déploiement de votre site"
deployTitle = "Déployer"
deployText = "Déployer votre site web sur l'IPFS"

# Frameworks Area Section
[Languages.fr.params.frameworks]
title = "De nombreux sites et frameworks sont pris en charge"
imagesFirstRow = ["wordpress.png", "jekyll.png", "publii.jpg", "docusaurus.svg", "11ty.png", "nuxtjs.png"]
imagesSecondRow = ["angular-logo.png", "react.png", "vue.png", "hugo.jpg", "gatsby.jpg", "siteleaf.png"]

# IPFS Explanation Section
[Languages.fr.params.ipfs]
title = "C'est quoi l'IPFS ?"
description = "IPFS permet aux utilisateurs d'héberger et de recevoir du contenu d'une manière similaire à BitTorrent. Par opposition à un serveur central, IPFS est construit autour d'un système décentralisé d'utilisateurs-opérateurs qui détiennent une partie de l'ensemble des données, créant ainsi un système résilient de stockage et de partage de fichiers. Tout utilisateur du réseau peut servir un fichier par son adresse de contenu, et les autres pairs du réseau peuvent trouver et demander ce contenu à tout nœud qui le possède en utilisant une table de hachage distribuée (DHT)."

# Why Dhost Section
[Languages.fr.params.whyDhost]
title = "Pourquoi DHost ?"

[[Languages.fr.params.whyDhost.perks]]
name = "fast"
text = "Rapide à mettre en place"
image = "fast.png"

[[Languages.fr.params.whyDhost.perks]]
name = "decentralized"
text = "Intégration dans le réseau IPFS"
image = "decentralized.png"

[[Languages.fr.params.whyDhost.perks]]
name = "security"
text = "Protection de vos informations"
image = "security.png"

[[Languages.fr.params.whyDhost.perks]]
name = "rgpd"
text = "Conformité aux normes RGPD"
image = "rgpd.png"

[[Languages.fr.params.whyDhost.perks]]
name = "easy"
text = "Facile d'utilisation"
image = "easy.png"

[[Languages.fr.params.whyDhost.perks]]
name = "sci-fi"
text = "Entrez dans le futur du web avec DHost"
image = "sci-fi.png"

# Deploy Section
[Languages.fr.params.deploy]
title = "Déployer votre propre site"

# Footer
[Languages.fr.params.footer]
legalNotice = "Mentions légales"
privacyPolicy = "Politique de confidentialité"

############# 2 - Site in ENGLISH
[Languages.en]
languageCode = "en-us"
title = "Dhost"
dateFormat = "January 2, 2006"
home = "EN Home"
logo = "/imgs/dhostlogo.png"

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Decentralized hosting for your"
headingWebsite = "website"
description = "Dhost makes it easy to build websites and apps on the new open web: permissionless, trustless, censorship resistant, and free of centralized gatekeepers."
button  = true
btnGetStartedText = "Get Started"
btnGetStartedURL  = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
btnLearnMoreText = "Learn More"
btnLearnMoreURL  = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

# Deploy Section
[Languages.en.params.process]
title = "Decentralyze your app"
uploadText = "Choose the source of your website"
buildTitle = "Check build options"
buildText = "Adapt your settings to mold your site deployment"
deployTitle = "Deploy"
deployText = "Deploy your website on IPFS"

# Frameworks Area Section
[Languages.en.params.frameworks]
title = "Many sites and frameworks are supported"
imagesFirstRow = ["wordpress.png", "jekyll.png", "publii.jpg", "docusaurus.svg", "11ty.png", "nuxtjs.png"]
imagesSecondRow = ["angular-logo.png", "react.png", "vue.png", "hugo.jpg", "gatsby.jpg", "siteleaf.png"]

# IPFS Explanation Section
[Languages.en.params.ipfs]
title = "What's the IPFS ?"
description = "IPFS allows users to host and receive content in a manner similar to BitTorrent. As opposed to a centrally located server, IPFS is built around a decentralized system of user-operators who hold a portion of the overall data, creating a resilient system of file storage and sharing. Any user in the network can serve a file by its content address, and other peers in the network can find and request that content from any node who has it using a distributed hash table (DHT)."

# Why Dhost Section
[Languages.en.params.whyDhost]
title = "Why DHost ?"

[[Languages.en.params.whyDhost.perks]]
name = "fast"
text = "Quick to set up"
image = "fast.png"

[[Languages.en.params.whyDhost.perks]]
name = "decentralized"
text = "Integration into the IPFS network"
image = "decentralized.png"

[[Languages.en.params.whyDhost.perks]]
name = "security"
text = "Protection of your information"
image = "security.png"

[[Languages.en.params.whyDhost.perks]]
name = "rgpd"
text = "Compliance with RGPD standards"
image = "rgpd.png"

[[Languages.en.params.whyDhost.perks]]
name = "easy"
text = "Easy to use"
image = "easy.png"

[[Languages.en.params.whyDhost.perks]]
name = "sci-fi"
text = "Enter the future of the web with DHost"
image = "sci-fi.png"

# Deploy Section
[Languages.en.params.deploy]
title = "Deploy your own site"

# Footer
[Languages.en.params.footer]
legalNotice = "Legal Notice"
privacyPolicy = "Privacy Policy"